#!/bin/bash
echo 1621012023 - Abdulkerim Köse
echo Dizinde $(ls -1 | wc -l) dosya var,$1 dosyası : $(wc -c < $1) bayt, $(wc -w < $1) kelime , $(wc -m < $1) karakter , $(wc -l < $1) satır.
echo Dizinde $(ls -1 | wc -l) dosya var,$1 dosyası : $(wc -c < $1) bayt, $(wc -w < $1) kelime , $(wc -m < $1) karakter , $(wc -l < $1) satır. > 1621012023.txt
chmod -rwx+r 1621012023.txt
